### ISSUE TITLE
Conflict between `--spacing-*` and Tailwind container width utilities like `w-md`

### ISSUE THREAD

**Issue by Lomathsus** [songkeys/tailwind-preset-mantine#24]
>  "@mantine/core": "^7.17.3",
> "tailwind-preset-mantine": "^2.0.5",

After changing the values of `--spacing-*`, I found that Tailwind width utilities such as `w-xs`, `w-sm`, `w-md`, `w-lg`, and `w-xl` no longer work as expected.

For example, `w-md` is now compiled to:

```css
.w-md {
  width: var(--spacing-md);
}
```

This happens because `--spacing-md` is mapped to `--mantine-spacing-md`. However, the expected behavior is:

```css

.w-md {
  width: var(--container-md);
}
```

This conflict makes it impossible to use these width utilities for container sizing as intended.

I've tried for quite a while to resolve this conflict, but haven't been able to find a solution.

Would appreciate any guidance or potential fixes on how to avoid this overlap.
